// Used to be in Xamarin.Android.Support.Compat
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.Util.ArrayMap))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.Util.CircularArray))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.Util.CircularIntArray))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.Util.LongSparseArray))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.Util.LruCache))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.Util.SimpleArrayMap))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.Util.SparseArrayCompat))]

// Used to be in Xamarin.Android.Support.Core.UI
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.View.AbsSavedState))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.View.AsyncLayoutInflater))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.View.NestedScrollingChildHelper))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.View.NestedScrollingParentHelper))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.View.PagerAdapter))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.View.PagerTabStrip))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.View.PagerTitleStrip))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.View.ViewPager))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.View.Animation.FastOutLinearInInterpolator))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.View.Animation.FastOutSlowInInterpolator))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.View.Animation.LinearOutSlowInInterpolator))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.Widget.AutoScrollHelper))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.Widget.CircularProgressDrawable))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.Widget.ContentLoadingProgressBar))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.Widget.CursorAdapter))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.Widget.CursorFilter))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.Widget.CursorFilterICursorFilterClientExtensions))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.Widget.DrawerLayout))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.Widget.ExploreByTouchHelper))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.Widget.ListViewAutoScrollHelper))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.Widget.NestedScrollView))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.Widget.ResourceCursorAdapter))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.Widget.SimpleCursorAdapter))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.Widget.SimpleCursorAdapterICursorToStringConverterExtensions))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.Widget.SlidingPaneLayout))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.Widget.SwipeRefreshLayout))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.Widget.ViewDragHelper))]

// Used to be in Xamarin.Android.Support.Core.Util
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.App.AppLaunchChecker))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.App.FrameMetricsAggregator))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.App.NavUtils))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.App.TaskStackBuilder))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.Content.AsyncTaskLoader))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.Content.CursorLoader))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.Content.FileProvider))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.Content.Loader))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.Content.LocalBroadcastManager))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.Content.MimeTypeFilter))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.Content.PermissionChecker))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.Graphics.ColorUtils))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.Graphics.Drawable.RoundedBitmapDrawable))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.Graphics.Drawable.RoundedBitmapDrawableFactory))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.Math.MathUtils))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.Print.PrintHelper))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.Provider.DocumentFile))]

// Used to be in Xamarin.Android.Support.Fragment
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V4.App.LoaderManager))]
