[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V14.Preferences.EditTextPreferenceDialogFragment))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V14.Preferences.ListPreferenceDialogFragment))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V14.Preferences.MultiSelectListPreference))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V14.Preferences.MultiSelectListPreferenceDialogFragment))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V14.Preferences.PreferenceDialogFragment))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V14.Preferences.PreferenceFragment))]
[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Android.Support.V14.Preferences.SwitchPreference))]
